In [1]:
pip install --upgrade tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
# Building a graph
a = tf.constant(2)
b = tf.constant(4)
c = a+b
print(c)

Tensor("add_2:0", shape=(), dtype=int32)


In [6]:
# Running a computational graph
ssn = tf.compat.v1.Session()
ssn.run(c)

6

In [9]:
x1 = tf.constant([1,2,4,5])
x2 = tf.constant([2,3,4,5])
result = x1*x2 # result = tf.multiply(x1,x2)
print(result)

Tensor("mul_1:0", shape=(4,), dtype=int32)


In [8]:
ssn.run(result)

array([ 2,  6, 16, 25])

In [10]:
# Placeholder: not providing values at the time of declaration but providing values later at the time of execution
a = tf.compat.v1.placeholder(tf.float32)
b = tf.compat.v1.placeholder(tf.float32)
c = a+b
print(c)

Tensor("add_3:0", dtype=float32)


In [12]:
ssn.run(c,{a:1,b:4})

5.0

In [13]:
# placeholder is very useful when we want to give different input values
ssn.run(c,{a:[1,2,3],b:[4,2,1]})

array([5., 4., 4.], dtype=float32)

In [14]:
ssn.run(c,{a:[1,2],b:[4,2]})

array([5., 4.], dtype=float32)

In [15]:
ssn.run(c,{a:1,b:2})

3.0

In [17]:
# Variable

x = tf.compat.v1.Variable([1])
w = tf.compat.v1.Variable([3])
c = x*w
init = tf.compat.v1.global_variables_initializer()
ssn.run(init)
ssn.run(c)

array([3])