In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

In [2]:
os.getcwd()

'C:\\Users\\pmgho'

In [3]:
os.chdir('C:\\Users\\pmgho\\OneDrive\\Desktop\\image_classification_using_multilayer_perceptron(MLP)')

In [4]:
dataset_path = os.listdir('Room_Data')
room_types = os.listdir('Room_Data')
print (room_types)  #what kinds of rooms are in this dataset

print("Types of rooms found: ", len(dataset_path))

['Bedroom', 'Dinning', 'Livingroom']
Types of rooms found:  3


In [6]:
rooms = []
for item in room_types:
 # Get all the file names
 all_rooms = os.listdir('Room_Data' + '/' +item)
 #print(all_rooms)

 # Add them to the list
 for room in all_rooms:
    rooms.append((item, str('Room_Data' + '/' +item) + '/' + room))
    print(rooms[:1])

[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom', 'Room_Data/Bedroom/bed_1.jpg')]
[('Bedroom

- Build a dataframe 

In [7]:
rooms_df = pd.DataFrame(data=rooms, columns=['room type', 'image'])
print(rooms_df.head())
print(rooms_df.tail())

  room type                          image
0   Bedroom    Room_Data/Bedroom/bed_1.jpg
1   Bedroom   Room_Data/Bedroom/bed_10.jpg
2   Bedroom  Room_Data/Bedroom/bed_100.jpg
3   Bedroom  Room_Data/Bedroom/bed_101.jpg
4   Bedroom  Room_Data/Bedroom/bed_102.jpg
      room type                               image
572  Livingroom  Room_Data/Livingroom/living_95.jpg
573  Livingroom  Room_Data/Livingroom/living_96.jpg
574  Livingroom  Room_Data/Livingroom/living_97.jpg
575  Livingroom  Room_Data/Livingroom/living_98.jpg
576  Livingroom  Room_Data/Livingroom/living_99.jpg


- Let's check how many samples for each category are present

In [8]:
print("Total number of rooms in the dataset: ", len(rooms_df))

Total number of rooms in the dataset:  577


In [10]:
room_count = rooms_df['room type'].value_counts()
print("rooms in each category: ")
print(room_count)

rooms in each category: 
room type
Dinning       220
Livingroom    181
Bedroom       176
Name: count, dtype: int64


In [12]:
import cv2
path = 'Room_Data/'


im_size = 100

images = []
labels = []

for i in room_types:
    data_path = path + str(i) 
    filenames = [i for i in os.listdir(data_path) ]
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)  
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)

- Transform the image array to a numpy type

In [13]:
images = np.array(images)
images.shape

(577, 100, 100, 3)

In [14]:
images = images.astype('float32') / 255.0

In [15]:
images.shape

(577, 100, 100, 3)

In [16]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
y=rooms_df['room type'].values
print(y[:5])

['Bedroom' 'Bedroom' 'Bedroom' 'Bedroom' 'Bedroom']


In [17]:
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 

In [22]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
y = y.reshape(-1, 1)
onehotencoder = OneHotEncoder(sparse_output=False)
Y = onehotencoder.fit_transform(y)
print(Y.shape)

(577, 3)


In [24]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
images, Y = shuffle(images, Y, random_state=1)
train_x, test_x, train_y, test_y = train_test_split(images, Y, test_size=0.05, random_state=415)

#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(548, 100, 100, 3)
(548, 3)
(29, 100, 100, 3)
(29, 3)


In [26]:
train_x=np.reshape(train_x,(548,30000))
print(train_x.shape)

test_x=np.reshape(test_x,(29,30000))
test_x.shape

(548, 30000)


(29, 30000)

- hyper Parameters

In [27]:
learning_rate = 0.001

- Network Parameters

In [28]:
n_hidden_1 = 256 # 1st layer has 256 neurons
n_hidden_2 = 256 # 2nd layer has 256 neurons
n_input = 30000 #  data input (img shape: 100*100*3)
n_classes = 3 # total classes (3)

In [30]:
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Dense(n_hidden_1, activation='relu', input_shape=(n_input,)),
    layers.Dense(n_hidden_2, activation='relu'),
    layers.Dense(n_classes, activation='softmax')
])

C:\Users\pmgho\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


- Store layers weight & bias

In [32]:
import tensorflow as tf

weights = {
    'h1': tf.Variable(tf.random.normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random.normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random.normal([n_hidden_2, n_classes]))
}

biases = {
    'b1': tf.Variable(tf.random.normal([n_hidden_1])),
    'b2': tf.Variable(tf.random.normal([n_hidden_2])),
    'out': tf.Variable(tf.random.normal([n_classes]))
}

- Create model

In [33]:
def multilayer_perceptron(x, weights, biases):
    # Hidden layer with RELU activation
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])  #matmul on x and w , then adding it with bias # summation
    layer_1 = tf.nn.relu(layer_1)   # activation function
    
    # Hidden layer with RELU activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
    
    # Output layer with linear activation
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    out_layer = tf.nn.softmax(out_layer)
    return out_layer

- Construct model

In [35]:
x = tf.constant(train_x, dtype=tf.float32)

In [36]:
pred = multilayer_perceptron(x, weights, biases)

In [37]:
pred


<tf.Tensor: shape=(548, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)>

In [40]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# placeholders
x = tf.placeholder(tf.float32, [None, n_input])
y_ = tf.placeholder(tf.float32, [None, n_classes])

# weights
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}

# biases
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# forward pass
def multilayer_perceptron(x):
    layer_1 = tf.nn.relu(tf.matmul(x, weights['h1']) + biases['b1'])
    layer_2 = tf.nn.relu(tf.matmul(layer_1, weights['h2']) + biases['b2'])
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

pred = multilayer_perceptron(x)

# loss
cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y_)
)

# optimizer
optimizer = tf.train.AdamOptimizer(learning_rate=0.001).minimize(cost)


Instructions for updating:
non-resource variables are not supported in the long term
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.




In [41]:
def multilayer_perceptron(x, weights, biases):
    # Hidden layer with RELU activation
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])  #matmul on x and w , then adding it with bias # summation
    layer_1 = tf.nn.relu(layer_1)   # activation function
    
    # Hidden layer with RELU activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
    
    # Output layer with linear activation
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    out_layer = tf.nn.softmax(out_layer)
    return out_layer

In [42]:
pred = multilayer_perceptron(x, weights, biases)

In [44]:
# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y_))   #. pred is the output of MLP . Y is the placeholder which will hold the target output
# cross-entropy for calculating error

# cross-entropy for calculating error
#cost = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(pred),reduction_indices=[1]))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

In [45]:
# Initializing the variables
init = tf.global_variables_initializer()
#create an empty list to store the cost history and accuracy history
cost_history = []
accuracy_history = []
# Launch the graph

In [46]:
# the execution
sess = tf.Session()
sess.run(init)

In [49]:
cost_history = []
n_epochs = 20

for i in range(n_epochs):
    _, c = sess.run([optimizer, cost], feed_dict={x: train_x, y_: train_y})
    
    cost_history.append(c)   # better than np.append
    print('epoch:', i, '- cost:', c)

epoch: 0 - cost: 1.1718827
epoch: 1 - cost: 1.1718827
epoch: 2 - cost: 1.1718827
epoch: 3 - cost: 1.1718827
epoch: 4 - cost: 1.1718827
epoch: 5 - cost: 1.1718827
epoch: 6 - cost: 1.1718827
epoch: 7 - cost: 1.1718827
epoch: 8 - cost: 1.1718827
epoch: 9 - cost: 1.1718827
epoch: 10 - cost: 1.1718827
epoch: 11 - cost: 1.1718827
epoch: 12 - cost: 1.1718827
epoch: 13 - cost: 1.1718827
epoch: 14 - cost: 1.1718827
epoch: 15 - cost: 1.1718827
epoch: 16 - cost: 1.1718827
epoch: 17 - cost: 1.1718827
epoch: 18 - cost: 1.1718827
epoch: 19 - cost: 1.1718827


- checkig accuracy of model on test data

In [51]:
import numpy as np

# Convert properly
test_y = np.array(test_y)

# Ensure correct dtype
test_x = test_x.astype(np.float32)
test_y = test_y.astype(np.float32)

# Normalize
test_x = test_x / 255.0

# Accuracy calculation
correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

# Run session
print("Accuracy:", sess.run(accuracy, feed_dict={x: test_x, y_: test_y}))

Accuracy: 0.41379312


- take input from user and predict the result

In [57]:
import cv2
import numpy as np

img = cv2.imread(r'C:\\Users\\pmgho\\OneDrive\\Desktop\\image_classification_using_multilayer_perceptron(MLP)\\Room_Data\Dinning\\din_24.jpg')

if img is None:
    print("Image not loaded. Check path!")
else:
    img = cv2.resize(img, (100, 100))
    IMG = np.reshape(img, (1, 30000))
    print("Image ready:", IMG.shape)

Image ready: (1, 30000)


In [58]:
import cv2
import numpy as np

img = cv2.imread(r'C:\\Users\\pmgho\\OneDrive\\Desktop\\image_classification_using_multilayer_perceptron(MLP)\\Room_Data\Dinning\\din_24.jpg')

if img is None:
    print("Image not loaded. Check path!")
else:
    img = cv2.resize(img, (100, 100))

    IMG = np.reshape(img, (1, 30000))

    
    IMG = IMG / 255.0
    IMG = IMG.astype(np.float32)

    # Prediction
    pred_y = sess.run(pred, feed_dict={x: IMG})

    print("Raw Output:", pred_y)
    print("Predicted Class:", np.argmax(pred_y))

Raw Output: [[0. 1. 0.]]
Predicted Class: 1


In [59]:
IMG = IMG / 255.0

In [60]:
IMG

array([[0.00118416, 0.00175317, 0.00196847, ..., 0.00070742, 0.00126105,
        0.0018762 ]], dtype=float32)

In [61]:
classes = ['Bedroom', 'Dinning', 'Kitchen']   # adjust based on your dataset

pred_class = np.argmax(pred_y)
print("Predicted:", classes[pred_class])

Predicted: Dinning
